crosoft.Extensions.Logging": "2.0.2",
          "Microsoft.Extensions.Logging.Abstractions": "2.0.2",
          "Microsoft.Extensions.Logging.AzureAppServices": "2.0.2",
          "Microsoft.Extensions.Logging.Configuration": "2.0.2",
          "Microsoft.Extensions.Logging.Console": "2.0.2",
          "Microsoft.Extensions.Logging.Debug": "2.0.2",
          "Microsoft.Extensions.Logging.EventSource": "2.0.2",
          "Microsoft.Extensions.Logging.TraceSource": "2.0.2",
          "Microsoft.Extensions.ObjectPool": "2.0.0",
          "Microsoft.Extensions.Options": "2.0.2",
          "Microsoft.Extensions.Options.ConfigurationExtensions": "2.0.2",
          "Microsoft.Extensions.Primitives": "2.0.0",
          "Microsoft.Extensions.WebEncoders": "2.0.2",
  