E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.deps.json
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.json
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.dev.json
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csproj.CoreCompileInputs.cache
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfoInputs.cache
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfo.cs
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Certificate\cas.clientservice.pfx
E:\Projects\DNC\Manulife.DNC.MSAD\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csprojAssemblyReference.cache
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\certificate\cas.clientservice.pfx
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.deps.json
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.json
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.dev.json
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csprojAssemblyReference.cache
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csproj.CoreCompileInputs.cache
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfoInputs.cache
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfo.cs
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
E:\Projects\DNC\EDC.IdentityServer4.Demo\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\certificate\cas.clientservice.pfx
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.deps.json
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.json
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.dev.json
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csprojAssemblyReference.cache
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csproj.CoreCompileInputs.cache
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfoInputs.cache
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfo.cs
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
C:\Users\Lenovo\Downloads\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\certificate\cas.clientservice.pfx
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.deps.json
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.json
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.runtimeconfig.dev.json
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.dll
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\bin\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.pdb
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csprojAssemblyReference.cache
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.csproj.CoreCompileInputs.cache
D:\project\平台\跨操作系统平台\认证\EDC.IdentityServer4.Demo-master\EDC.IdentityServer4.Demo-master\Manulife.DNC.MSAD.IdentityServer4Test\obj\Debug\netcoreapp2.0\Manulife.DNC.MSAD.IdentityServer4Test.AssemblyInfoInputs.cache
D:\project\平台\跨操作系