y.Cryptography.Apple/4.3.0": {
      "sha512": "kVXCuMTrTlxq4XOOMAysuNwsXWpYeboGddNGpIgNSZmv1b6r/s/DPk0fYMB7Q5Qo4bY68o48jt4T4y5BVecbCQ==",
      "type": "package",
      "path": "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.apple/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.apple.4.3.0.nupkg.sha512",
        "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.apple.nuspec",
        "runtimes/osx.10.10-x64/native/System.Security.Cryptography.Native.Apple.dylib"
      ]
    },
    "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
      "sha512": "X7IdhILzr4ROXd8mI1BUCQMSHSQwelUlBjF1JyTKCjXaOGn2fB4EKBxQbCK2VjO3WaWIdlXZL3W6TiIVnrhX4g==",
      "type": "package",
      "path": "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.openssl/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg.sha512",
        "runtime.osx.10.10-x64.runtime.native.system.security.cryptography.openssl.nuspec",
        "runtimes/osx.10.10-x64/native/System.Security.Cryptography.Native.OpenSsl.dylib"
      ]
    },
    "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
      "sha512": "nyFNiCk/r+VOiIqreLix8yN+q3Wga9+SE8BCgkf+2BwEKiNx6DyvFjCgkfV743/grxv8jHJ8gUK4XEQw7yzRYg==",
      "type": "package",
      "path": "runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg.sha512",
        "runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl.nuspec",
        "runtimes/rhel.7-x64/native/System.Security.Cryptography.Native.OpenSsl.so"
      ]
    },
    "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
      "sha512": "ytoewC6wGorL7KoCAvRfsgoJPJbNq+64k2SqW6JcOAebWsFUvCCYgfzQMrnpvPiEl4OrblUlhF2ji+Q1+SVLrQ==",
      "type": "package",
      "path": "runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg.sha512",
        "runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl.nuspec",
        "runtimes/ubuntu.14.04-x64/native/System.Security.Cryptography.Native.OpenSsl.so"
      ]
    },
    "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
      "sha512": "I8bKw2I8k58Wx7fMKQJn2R8lamboCAiHfHeV/pS65ScKWMMI0+wJkLYlEKvgW1D/XvSl/221clBoR2q9QNNM7A==",
      "type": "package",
      "path": "runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg.sha512",
        "runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl.nuspec",
        "runtimes/ubuntu.16.04-x64/native/System.Security.Cryptography.Native.OpenSsl.so"
      ]
    },
    "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
      "sha512": "VB5cn/7OzUfzdnC8tqAIMQciVLiq2epm2NrAm1E9OjNRyG4lVhfR61SMcLizejzQP8R8Uf/0l5qOIbUEi+RdEg==",
      "type": "package",
      "path": "runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg.sha512",
        "runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl.nuspec",
        "runtimes/ubuntu.16.10-x64/native/System.Security.Cryptography.Native.OpenSsl.so"
      ]
    },
    "runtime.win-arm64.runtime.native.System.Data.SqlClient.sni/4.4.0": {
      "sha512": "LbrynESTp3bm5O/+jGL8v0Qg5SJlTV08lpIpFesXjF6uGNMWqFnUQbYBJwZTeua6E/Y7FIM1C54Ey1btLWupdg==",
      "type": "package",
      "path": "runtime.win-arm64.runtime.native.system.data.sqlclient.sni/4.4.0",
      "files": [
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.win-arm64.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg.sha512",
        "runtime.win-arm64.runtime.native.system.data.sqlclient.sni.nuspec",
        "runtimes/win-arm64/native/sni.dll",
        "useSharedDesignerContext.txt",
        "version.txt"
      ]
    },
    "runtime.win-x64.runtime.native.System.Data.SqlClient.sni/4.4.0": {
      "sha512": "38ugOfkYJqJoX9g6EYRlZB5U2ZJH51UP8ptxZgdpS07FgOEToV+lS11ouNK2PM12Pr6X/PpT5jK82G3DwH/SxQ==",
      "type": "package",
      "path": "runtime.win-x64.runtime.native.system.data.sqlclient.sni/4.4.0",
      "files": [
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.win-x64.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg.sha512",
        "runtime.win-x64.runtime.native.system.data.sqlclient.sni.nuspec",
        "runtimes/win-x64/native/sni.dll",
        "useSharedDesignerContext.txt",
        "version.txt"
      ]
    },
    "runtime.win-x86.runtime.native.System.Data.SqlClient.sni/4.4.0": {
      "sha512": "YhEdSQUsTx+C8m8Bw7ar5/VesXvCFMItyZF7G1AUY+OM0VPZUOeAVpJ4Wl6fydBGUYZxojTDR3I6Bj/+BPkJNA==",
      "type": "package",
      "path": "runtime.win-x86.runtime.native.system.data.sqlclient.sni/4.4.0",
      "files": [
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "runtime.win-x86.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg.sha512",
        "runtime.win-x86.runtime.native.system.data.sqlclient.sni.nuspec",
        "runtimes/win-x86/native/sni.dll",
        "useSharedDesignerContext.txt",
        "version.txt"
      ]
    },
    "System.AppContext/4.3.0": {
      "sha512": "fKC+rmaLfeIzUhagxY17Q9siv/sPrjjKcfNg1Ic8IlQkZLipo8ljcaZQu4VtI4Jqbzjc2VTjzGLF6WmsRXAEgA==",
      "type": "package",
      "path": "system.appcontext/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net46/System.AppContext.dll",
        "lib/net463/System.AppContext.dll",
        "lib/netcore50/System.AppContext.dll",
        "lib/netstandard1.6/System.AppContext.dll",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net46/System.AppContext.dll",
        "ref/net463/System.AppContext.dll",
        "ref/netstandard/_._",
        "ref/netstandard1.3/System.AppContext.dll",
        "ref/netstandard1.3/System.AppContext.xml",
        "ref/netstandard1.3/de/System.AppContext.xml",
        "ref/netstandard1.3/es/System.AppContext.xml",
        "ref/netstandard1.3/fr/System.AppContext.xml",
        "ref/netstandard1.3/it/System.AppContext.xml",
        "ref/netstandard1.3/ja/System.AppContext.xml",
        "ref/netstandard1.3/ko/System.AppContext.xml",
        "ref/netstandard1.3/ru/System.AppContext.xml",
        "ref/netstandard1.3/zh-hans/System.AppContext.xml",
        "ref/netstandard1.3/zh-hant/System.AppContext.xml",
        "ref/netstandard1.6/System.AppContext.dll",
        "ref/netstandard1.6/System.AppContext.xml",
        "ref/netstandard1.6/de/System.AppContext.xml",
        "ref/netstandard1.6/es/System.AppContext.xml",
        "ref/netstandard1.6/fr/System.AppContext.xml",
        "ref/netstandard1.6/it/System.AppContext.xml",
        "ref/netstandard1.6/ja/System.AppContext.xml",
        "ref/netstandard1.6/ko/System.AppContext.xml",
        "ref/netstandard1.6/ru/System.AppContext.xml",
        "ref/netstandard1.6/zh-hans/System.AppContext.xml",
        "ref/netstandard1.6/zh-hant/System.AppContext.xml",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._",
        "runtimes/aot/lib/netcore50/System.AppContext.dll",
        "system.appcontext.4.3.0.nupkg.sha512",
        "system.appcontext.nuspec"
      ]
    },
    "System.Buffers/4.5.0": {
      "sha512": "pL2ChpaRRWI/p4LXyy4RgeWlYF2sgfj/pnVMvBqwNFr5cXg7CXNnWZWxrOONLg8VGdFB8oB+EG2Qw4MLgTOe+A==",
      "type": "package",
      "path": "system.buffers/4.5.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "LICENSE.TXT",
        "THIRD-PARTY-NOTICES.TXT",
        "lib/netcoreapp2.0/_._",
        "lib/netstandard1.1/System.Buffers.dll",
        "lib/netstandard1.1/System.Buffers.xml",
        "lib/netstandard2.0/System.Buffers.dll",
        "lib/netstandard2.0/System.Buffers.xml",
        "lib/uap10.0.16299/_._",
        "ref/net45/System.Buffers.dll",
        "ref/net45/System.Buffers.xml",
        "ref/netcoreapp2.0/_._",
        "ref/netstandard1.1/System.Buffers.dll",
        "ref/netstandard1.1/System.Buffers.xml",
        "ref/netstandard2.0/System.Buffers.dll",
        "ref/netstandard2.0/System.Buffers.xml",
        "ref/uap10.0.16299/_._",
        "system.buffers.4.5.0.nupkg.sha512",
        "system.buffers.nuspec",
        "useSharedDesignerContext.txt",
        "version.txt"
      ]
    },
    "System.Collections/4.3.0": {
      "sha512": "3Dcj85/TBdVpL5Zr+gEEBUuFe2icOnLalmEh9hfck1PTYbbyWuZgh4fmm2ysCLTrqLQw6t3TgTyJ+VLp+Qb+Lw==",
      "type": "package",
      "path": "system.collections/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net45/_._",
        "lib/portable-net45+win8+wp8+wpa81/_._",
        "lib/win8/_._",
        "lib/wp80/_._",
        "lib/wpa81/_._",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net45/_._",
        "ref/netcore50/System.Collections.dll",
        "ref/netcore50/System.Collections.xml",
        "ref/netcore50/de/System.Collections.xml",
        "ref/netcore50/es/System.Collections.xml",
        "ref/netcore50/fr/System.Collections.xml",
        "ref/netcore50/it/System.Collections.xml",
        "ref/netcore50/ja/System.Collections.xml",
        "ref/netcore50/ko/System.Collections.xml",
        "ref/netcore50/ru/System.Collections.xml",
        "ref/netcore50/zh-hans/System.Collections.xml",
        "ref/netcore50/zh-hant/System.Collections.xml",
        "ref/netstandard1.0/System.Collections.dll",
        "ref/netstandard1.0/System.Collections.xml",
        "ref/netstandard1.0/de/System.Collections.xml",
        "ref/netstandard1.0/es/System.Collections.xml",
        "ref/netstandard1.0/fr/System.Collections.xml",
        "ref/netstandard1.0/it/System.Collections.xml",
        "ref/netstandard1.0/ja/System.Collections.xml",
        "ref/netstandard1.0/ko/System.Collections.xml",
        "ref/netstandard1.0/ru/System.Collections.xml",
        "ref/netstandard1.0/zh-hans/System.Collections.xml",
        "ref/netstandard1.0/zh-hant/System.Collections.xml",
        "ref/netstandard1.3/System.Collections.dll",
        "ref/netstandard1.3/System.Collections.xml",
        "ref/netstandard1.3/de/System.Collections.xml",
        "ref/netstandard1.3/es/System.Collections.xml",
        "ref/netstandard1.3/fr/System.Collections.xml",
        "ref/netstandard1.3/it/System.Collections.xml",
        "ref/netstandard1.3/ja/System.Collections.xml",
        "ref/netstandard1.3/ko/System.Collections.xml",
        "ref/netstandard1.3/ru/System.Collections.xml",
        "ref/netstandard1.3/zh-hans/System.Collections.xml",
        "ref/netstandard1.3/zh-hant/System.Collections.xml",
        "ref/portable-net45+win8+wp8+wpa81/_._",
        "ref/win8/_._",
        "ref/wp80/_._",
        "ref/wpa81/_._",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._",
        "system.collections.4.3.0.nupkg.sha512",
        "system.collections.nuspec"
      ]
    },
    "System.Collections.Concurrent/4.3.0": {
      "sha512": "ztl69Xp0Y/UXCL+3v3tEU+lIy+bvjKNUmopn1wep/a291pVPK7dxBd6T7WnlQqRog+d1a/hSsgRsmFnIBKTPLQ==",
      "type": "package",
      "path": "system.collections.concurrent/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net45/_._",
        "lib/netcore50/System.Collections.Concurrent.dll",
        "lib/netstandard1.3/System.Collections.Concurrent.dll",
        "lib/portable-net45+win8+wpa81/_._",
        "lib/win8/_._",
        "lib/wpa81/_._",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net45/_._",
        "ref/netcore50/System.Collections.Concurrent.dll",
        "ref/netcore50/System.Collections.Concurrent.xml",
        "ref/netcore50/de/System.Collections.Concurrent.xml",
        "ref/netcore50/es/System.Collections.Concurrent.xml",
        "ref/netcore50/fr/System.Collections.Concurrent.xml",
        "ref/netcore50/it/System.Collections.Concurrent.xml",
        "ref/netcore50/ja/System.Collections.Concurrent.xml",
        "ref/netcore50/ko/System.Collections.Concurrent.xml",
        "ref/netcore50/ru/System.Collections.Concurrent.xml",
        "ref/netcore50/zh-hans/System.Collections.Concurrent.xml",
        "ref/netcore50/zh-hant/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/System.Collections.Concurrent.dll",
        "ref/netstandard1.1/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/de/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/es/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/fr/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/it/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/ja/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/ko/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/ru/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/zh-hans/System.Collections.Concurrent.xml",
        "ref/netstandard1.1/zh-hant/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/System.Collections.Concurrent.dll",
        "ref/netstandard1.3/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/de/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/es/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/fr/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/it/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/ja/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/ko/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/ru/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/zh-hans/System.Collections.Concurrent.xml",
        "ref/netstandard1.3/zh-hant/System.Collections.Concurrent.xml",
        "ref/portable-net45+win8+wpa81/_._",
        "ref/win8/_._",
        "ref/wpa81/_._",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._",
        "system.collections.concurrent.4.3.0.nupkg.sha512",
        "system.collections.concurrent.nuspec"
      ]
    },
    "System.Collections.Immutable/1.5.0": {
      "sha512": "EXKiDFsChZW0RjrZ4FYHu9aW6+P4MCgEDCklsVseRfhoO0F+dXeMSsMRAlVXIo06kGJ/zv+2w1a2uc2+kxxSaQ==",
      "type": "package",
      "path": "system.collections.immutable/1.5.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "LICENSE.TXT",
        "THIRD-PARTY-NOTICES.TXT",
        "lib/netstandard1.0/System.Collections.Immutable.dll",
        "lib/netstandard1.0/System.Collections.Immutable.xml",
        "lib/netstandard1.3/System.Collections.Immutable.dll",
        "lib/netstandard1.3/System.Collections.Immutable.xml",
        "lib/netstandard2.0/System.Collections.Immutable.dll",
        "lib/netstandard2.0/System.Collections.Immutable.xml",
        "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll",
        "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.xml",
        "system.collections.immutable.1.5.0.nupkg.sha512",
        "system.collections.immutable.nuspec",
        "useSharedDesignerContext.txt",
        "version.txt"
      ]
    },
    "System.Collections.NonGeneric/4.3.0": {
      "sha512": "prtjIEMhGUnQq6RnPEYLpFt8AtLbp9yq2zxOSrY7KJJZrw25Fi97IzBqY7iqssbM61Ek5b8f3MG/sG1N2sN5KA==",
      "type": "package",
      "path": "system.collections.nongeneric/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net46/System.Collections.NonGeneric.dll",
        "lib/netstandard1.3/System.Collections.NonGeneric.dll",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net46/System.Collections.NonGeneric.dll",
        "ref/netstandard1.3/System.Collections.NonGeneric.dll",
        "ref/netstandard1.3/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/de/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/es/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/fr/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/it/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/ja/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/ko/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/ru/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/zh-hans/System.Collections.NonGeneric.xml",
        "ref/netstandard1.3/zh-hant/System.Collections.NonGeneric.xml",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._",
        "system.collections.nongeneric.4.3.0.nupkg.sha512",
        "system.collections.nongeneric.nuspec"
      ]
    },
    "System.Collections.Specialized/4.3.0": {
      "sha512": "Epx8PoVZR0iuOnJJDzp7pWvdfMMOAvpUo95pC4ScH2mJuXkKA2Y4aR3cG9qt2klHgSons1WFh4kcGW7cSXvrxg==",
      "type": "package",
      "path": "system.collections.specialized/4.3.0",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net46/System.Collections.Specialized.dll",
        "lib/netstandard1.3/System.Collections.Specialized.dll",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net46/System.Collections.Specialized.dll",
        "ref/netstandard1.3/System.Collections.Specialized.dll",
        "ref/netstandard1.3/System.Collections.Specialized.xml",
        "ref/netstandard1.3/de/System.Collections.Specialized.xml",
        "ref/netstandard1.3/es/System.Collections.Specialized.xml",
        "ref/netstandard1.3/fr/System.Collections.Specialized.xml",
        "ref/netstandard1.3/it/System.Collections.Specialized.xml",
        "ref/netstandard1.3/ja/System.Collections.Specialized.xml",
        "ref/netstandard1.3/ko/System.Collections.Specialized.xml",
        "ref/netstandard1.3/ru/System.Collections.Specialized.xml",
        "ref/netstandard1.3/zh-hans/System.Collections.Specialized.xml",
        "ref/netstandard1.3/zh-hant/System.Collections.Specialized.xml",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._",
        "system.collections.specialized.4.3.0.nupkg.sha512",
        "system.collections.specialized.nuspec"
      ]
    },
    "System.ComponentModel.Annotations/4.5.0": {
      "sha512": "UxYQ3FGUOtzJ7LfSdnYSFd7+oEv6M8NgUatatIN2HxNtDdlcvFAf+VIq4Of9cDMJEJC0aSRv/x898RYhB4Yppg==",
      "type": "package",
      "path": "system.componentmodel.annota